-- Generated by nwg-displays on 2026-07-09 at 09:08:14. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@60.0",
    position = "1920x0",
    scale = 1.5000000000000004
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = true
})
