# Shell variables
# Generated by 'wal'
wallpaper="/home/urmum/.cache/wal/moonv1.png"

# Special
background='#090404'
foreground='#c1c0c0'
cursor='#c1c0c0'

# Colors
color0='#090404'
color1='#575757'
color2='#686868'
color3='#787878'
color4='#888888'
color5='#979797'
color6='#A7A7A7'
color7='#c1c0c0'
color8='#665353'
color9='#575757'
color10='#686868'
color11='#787878'
color12='#888888'
color13='#979797'
color14='#A7A7A7'
color15='#c1c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
