general {
  lock_cmd = $HOME/.config/quickshell/lockscreen/lock.sh
  before_sleep_cmd = $HOME/.config/quickshell/lockscreen/lock.sh
}

listener {
    timeout = 1200
    on-timeout = $HOME/.config/quickshell/lockscreen/lock.sh &
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
