-- Generated by nwg-displays on 2026-06-01 at 13:54:36. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "5",
    monitor = "eDP-1"
})
