# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#eedeea"

# Title color for boxes
theme[title]="#bac3ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#bac3ff"

# Background color of selected item in processes box
theme[selected_bg]="#bac3ff"

# Foreground color of selected item in processes box
theme[selected_fg]="#162778"

# Color of inactive/disabled text
theme[inactive_fg]="#d8bfd5"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ecb4ec"

# Cpu box outline color
theme[cpu_box]="#a08a9e"

# Memory/disks box outline color
theme[mem_box]="#a08a9e"

# Net up/down box outline color
theme[net_box]="#a08a9e"

# Processes box outline color
theme[proc_box]="#a08a9e"

# Box divider line and small boxes line color
theme[div_line]="#534152"

# Temperature graph colors
theme[temp_start]="#bac3ff"
theme[temp_mid]="#bac3ff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#bac3ff"
theme[cpu_mid]="#bac3ff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#bac3ff"
theme[free_mid]=""
theme[free_end]="#394379"

# Mem/Disk cached meter
theme[cached_start]="#ecb4ec"
theme[cached_mid]=""
theme[cached_end]="#623766"

# Mem/Disk available meter
theme[available_start]="#bac3ff"
theme[available_mid]=""
theme[available_end]="#303f90"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#bac3ff"
theme[download_mid]="#bac3ff"
theme[download_end]="#ecb4ec"

# Upload graph colors
theme[upload_start]="#bac3ff"
theme[upload_mid]="#bac3ff"
theme[upload_end]="#ecb4ec"
