# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e7e0ee"

# Title color for boxes
theme[title]="#99cbff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#9dcbfb"

# Background color of selected item in processes box
theme[selected_bg]="#99cbff"

# Foreground color of selected item in processes box
theme[selected_fg]="#003355"

# Color of inactive/disabled text
theme[inactive_fg]="#ccc2db"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d0bcfe"

# Cpu box outline color
theme[cpu_box]="#958da4"

# Memory/disks box outline color
theme[mem_box]="#958da4"

# Net up/down box outline color
theme[net_box]="#958da4"

# Processes box outline color
theme[proc_box]="#958da4"

# Box divider line and small boxes line color
theme[div_line]="#4a4458"

# Temperature graph colors
theme[temp_start]="#9dcbfb"
theme[temp_mid]="#99cbff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#9dcbfb"
theme[cpu_mid]="#99cbff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#9dcbfb"
theme[free_mid]=""
theme[free_end]="#124a73"

# Mem/Disk cached meter
theme[cached_start]="#d0bcfe"
theme[cached_mid]=""
theme[cached_end]="#4e3d75"

# Mem/Disk available meter
theme[available_start]="#99cbff"
theme[available_mid]=""
theme[available_end]="#004a78"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#9dcbfb"
theme[download_mid]="#99cbff"
theme[download_end]="#d0bcfe"

# Upload graph colors
theme[upload_start]="#9dcbfb"
theme[upload_mid]="#99cbff"
theme[upload_end]="#d0bcfe"
