theme[main_bg]="#000408"
theme[main_fg]="#AEC7BA"

theme[title]="#526664"
theme[hi_fg]="#6E7D77"
theme[selected_bg]="#526664"
theme[selected_fg]="#000408"

theme[inactive_fg]="#1C1E21"
theme[graph_text]="#3E4A4B"
theme[meter_bg]="#1C1E21"

theme[cpu_box]="#3A3C3E"
theme[mem_box]="#3E4A4B"
theme[net_box]="#526664"
theme[proc_box]="#637671"

theme[div_line]="#1C1E21"
theme[temp_start]="#3E4A4B"
theme[temp_mid]="#465858"
theme[temp_end]="#3A3C3E"

theme[cached_start]="#526664"
theme[cached_mid]="#6E7D77"
theme[cached_end]="#637671"

theme[download_start]="#6E7D77"
theme[download_mid]="#526664"
theme[download_end]="#3E4A4B"

theme[upload_start]="#637671"
theme[upload_mid]="#465858"
theme[upload_end]="#3A3C3E"
