theme[main_bg]="#000308"
theme[main_fg]="#C2CDC9"

theme[title]="#5E716D"
theme[hi_fg]="#697972"
theme[selected_bg]="#5E716D"
theme[selected_fg]="#000308"

theme[inactive_fg]="#1C1D20"
theme[graph_text]="#455757"
theme[meter_bg]="#1C1D20"

theme[cpu_box]="#3E4849"
theme[mem_box]="#455757"
theme[net_box]="#5E716D"
theme[proc_box]="#6E7F7A"

theme[div_line]="#1C1D20"
theme[temp_start]="#455757"
theme[temp_mid]="#4F6260"
theme[temp_end]="#3E4849"

theme[cached_start]="#5E716D"
theme[cached_mid]="#697972"
theme[cached_end]="#6E7F7A"

theme[download_start]="#697972"
theme[download_mid]="#5E716D"
theme[download_end]="#455757"

theme[upload_start]="#6E7F7A"
theme[upload_mid]="#4F6260"
theme[upload_end]="#3E4849"
