cursor            #a6c8ff
cursor_text_color #03305f

foreground            #e1e2e9
background            #0c0e13
selection_foreground  #273141
selection_background  #bdc7dc
url_color             #bdc7dc

#: black 000000 767676
color0  #111318
color8  #32353a
#: red cc0403 f2201f
color1  #a49e50
color9  #dad7b3
#: green 19cb00 23fd00
color2  #bdc7dc
color10 #d9e3f8
#: yellow cecb00 fffd00
color3  #dbbde2
color11 #f8d8ff
#: blue 0d73cc 1a8fff
color4  #234776
color12 #a6c8ff
#: magenta cb1ed1 fd28ff
color5  #3d4758
color13 #bdc7dc
#: cyan 0dcdcd 14ffff
color6  #553f5d
color14 #dbbde2
#: white dddddd ffffff
color7  #c4c6cf
color15 #e1e2e9

mark1_foreground #001c3b
mark1_background #d5e3ff
mark2_foreground #121c2b
mark2_background #d9e3f8
mark3_foreground #27132f
mark3_background #f8d8ff

active_tab_foreground #03305f
active_tab_background #a6c8ff
inactive_tab_foreground #d5e3ff
inactive_tab_background #234776

active_border_color #a6c8ff
inactive_border_color #03305f
# bell_border_color #ff5a00
