# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #AEC7BA

background #000408
foreground #AEC7BA

# color0 #01040A
# color1 #3A3C3E
# color2 #AEC7BA
# color3 #465858
# color4 #526664
# color5 #637671
# color6 #6E7D77
# color7 #AEC7BA
# color8 #606264
# color9 #3A3D41
# color10 #425658
# color11 #4F6F6F
# color12 #5E837E
# color13 #5E8A7E
# color14 #465858
# color15 #AEC7BA

mark1_foreground #587D6E
mark2_foreground #8BC7A8
mark3_foreground #587D6E


# color0 #01040A
# color1 #3A3C3E
# color2 #3E4A4B
# color3 #465858
# color4 #526664
# color5 #637671
# color6 #6E7D77
# color7 #AEC7BA
# color8 #1C1E21
# color9 #3A3D41
# color10 #425658
# color11 #4F6F6F
# color12 #5E837E
# color13 #5E8A7E
# color14 #88AA9C
# color15 #AEC7BA
