# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #C2CDC9

background #000308
foreground #AFB9B5

color0 #000309
color1 #3E4849
color2 #C2CDC9
color3 #4F6260
color4 #5E716D
color5 #6E7F7A
color6 #697972
color7 #C2CDC9
color8 #1C1D20
color9 #415456
color10 #4F6E6E
color11 #5F827E
color12 #538076
color13 #799F93
color14 #4F6260
color15 #C2CDC9

mark1_foreground #547969
mark2_foreground #9BCDBB
mark3_foreground #547969
