theme[main_bg]="{{background}}"
theme[main_fg]="{{foreground}}"

theme[title]="{{color4}}"
theme[hi_fg]="{{color6}}"
theme[selected_bg]="{{color4}}"
theme[selected_fg]="{{background}}"

theme[inactive_fg]="{{color8}}"
theme[graph_text]="{{color2}}"
theme[meter_bg]="{{color8}}"

theme[cpu_box]="{{color1}}"
theme[mem_box]="{{color2}}"
theme[net_box]="{{color4}}"
theme[proc_box]="{{color5}}"

theme[div_line]="{{color8}}"
theme[temp_start]="{{color2}}"
theme[temp_mid]="{{color3}}"
theme[temp_end]="{{color1}}"

theme[cached_start]="{{color4}}"
theme[cached_mid]="{{color6}}"
theme[cached_end]="{{color5}}"

theme[download_start]="{{color6}}"
theme[download_mid]="{{color4}}"
theme[download_end]="{{color2}}"

theme[upload_start]="{{color5}}"
theme[upload_mid]="{{color3}}"
theme[upload_end]="{{color1}}"
