--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/urmum/.cache/wal/wp2379096-ori-and-the-blind-forest-wallpapers.jpg"

-- Special
background="#080b14"
foreground="#c1c2c4"
cursor="#c1c2c4"

-- Colors
color0="#080b14"
color1="#1A4C5E"
color2="#124676"
color3="#083B86"
color4="#15518B"
color5="#276CA2"
color6="#3585B8"
color7="#c1c2c4"
color8="#585d6b"
color9="#1A4C5E"
color10="#124676"
color11="#083B86"
color12="#15518B"
color13="#276CA2"
color14="#3585B8"
color15="#c1c2c4"
